/** Client-side set code reference for autocomplete. Mirrors server/src/utils/set-codes.ts */

export interface SetEntry {
  code: string;
  name: string; // primary display name (first alias)
}

export const EN_SETS: SetEntry[] = [
  { code: 'BS1',       name: 'Base Set' },
  { code: 'JG',        name: 'Jungle' },
  { code: 'FO',        name: 'Fossil' },
  { code: 'BS2',       name: 'Base Set 2' },
  { code: 'TR',        name: 'Team Rocket' },
  { code: 'GH',        name: 'Gym Heroes' },
  { code: 'GC',        name: 'Gym Challenge' },
  { code: 'NEO1',      name: 'Neo Genesis' },
  { code: 'NEO2',      name: 'Neo Discovery' },
  { code: 'NEO3',      name: 'Neo Revelation' },
  { code: 'NEO4',      name: 'Neo Destiny' },
  { code: 'LC',        name: 'Legendary Collection' },
  { code: 'E1',        name: 'Expedition' },
  { code: 'E2',        name: 'Aquapolis' },
  { code: 'E3',        name: 'Skyridge' },
  { code: 'ADV1',      name: 'EX Ruby & Sapphire' },
  { code: 'ADV2',      name: 'EX Sandstorm' },
  { code: 'ADV3',      name: 'EX Dragon' },
  { code: 'ADV4',      name: 'EX Team Magma vs Aqua' },
  { code: 'ADV5',      name: 'EX Hidden Legends' },
  { code: 'ADV6',      name: 'EX FireRed & LeafGreen' },
  { code: 'ADV7',      name: 'EX Team Rocket Returns' },
  { code: 'ADV8',      name: 'EX Deoxys' },
  { code: 'ADV9',      name: 'EX Emerald' },
  { code: 'ADV10',     name: 'EX Unseen Forces' },
  { code: 'ADV11',     name: 'EX Delta Species' },
  { code: 'ADV12',     name: 'EX Legend Maker' },
  { code: 'ADV13',     name: 'EX Holon Phantoms' },
  { code: 'ADV14',     name: 'EX Crystal Guardians' },
  { code: 'ADV15',     name: 'EX Dragon Frontiers' },
  { code: 'ADV16',     name: 'EX Power Keepers' },
  { code: 'DP1',       name: 'Diamond & Pearl' },
  { code: 'DP2',       name: 'Mysterious Treasures' },
  { code: 'DP3',       name: 'Secret Wonders' },
  { code: 'DP4',       name: 'Great Encounters' },
  { code: 'DP5',       name: 'Majestic Dawn' },
  { code: 'DP6',       name: 'Legends Awakened' },
  { code: 'DP7',       name: 'Stormfront' },
  { code: 'PL1',       name: 'Platinum' },
  { code: 'PL2',       name: 'Rising Rivals' },
  { code: 'PL3',       name: 'Supreme Victors' },
  { code: 'PL4',       name: 'Arceus' },
  { code: 'HGSS1',     name: 'HeartGold SoulSilver' },
  { code: 'HGSS2',     name: 'Unleashed' },
  { code: 'HGSS3',     name: 'Undaunted' },
  { code: 'HGSS4',     name: 'Triumphant' },
  { code: 'BW1',       name: 'Black & White' },
  { code: 'BW2',       name: 'Emerging Powers' },
  { code: 'BW3',       name: 'Noble Victories' },
  { code: 'BW4',       name: 'Next Destinies' },
  { code: 'BW5',       name: 'Dark Explorers' },
  { code: 'BW6',       name: 'Dragons Exalted' },
  { code: 'BW7',       name: 'Boundaries Crossed' },
  { code: 'BW8',       name: 'Plasma Storm' },
  { code: 'BW9',       name: 'Plasma Freeze' },
  { code: 'BW10',      name: 'Plasma Blast' },
  { code: 'BW11',      name: 'Legendary Treasures' },
  { code: 'XY1',       name: 'XY Base' },
  { code: 'XY2',       name: 'Flashfire' },
  { code: 'XY3',       name: 'Furious Fists' },
  { code: 'XY4',       name: 'Phantom Forces' },
  { code: 'XY5',       name: 'Primal Clash' },
  { code: 'XY6',       name: 'Roaring Skies' },
  { code: 'XY7',       name: 'Ancient Origins' },
  { code: 'XY8',       name: 'BREAKthrough' },
  { code: 'XY9',       name: 'BREAKpoint' },
  { code: 'XY10',      name: 'Fates Collide' },
  { code: 'XY11',      name: 'Steam Siege' },
  { code: 'XY12',      name: 'Evolutions' },
  { code: 'SM1',       name: 'Sun & Moon' },
  { code: 'SM2',       name: 'Guardians Rising' },
  { code: 'SM3',       name: 'Burning Shadows' },
  { code: 'SM4',       name: 'Crimson Invasion' },
  { code: 'SM5',       name: 'Ultra Prism' },
  { code: 'SM6',       name: 'Forbidden Light' },
  { code: 'SM7',       name: 'Celestial Storm' },
  { code: 'SM8',       name: 'Lost Thunder' },
  { code: 'SM9',       name: 'Team Up' },
  { code: 'SM10',      name: 'Unbroken Bonds' },
  { code: 'SM11',      name: 'Unified Minds' },
  { code: 'SM12',      name: 'Cosmic Eclipse' },
  { code: 'SWSH1',     name: 'Sword & Shield' },
  { code: 'SWSH2',     name: 'Rebel Clash' },
  { code: 'SWSH3',     name: 'Darkness Ablaze' },
  { code: 'SWSH4',     name: 'Vivid Voltage' },
  { code: 'SWSH5',     name: 'Battle Styles' },
  { code: 'SWSH6',     name: 'Chilling Reign' },
  { code: 'SWSH7',     name: 'Evolving Skies' },
  { code: 'SWSH8',     name: 'Fusion Strike' },
  { code: 'SWSH9',     name: 'Brilliant Stars' },
  { code: 'SWSH10',    name: 'Astral Radiance' },
  { code: 'SWSH11',    name: 'Lost Origin' },
  { code: 'SWSH12',    name: 'Silver Tempest' },
  { code: 'SV1',       name: 'Scarlet & Violet' },
  { code: 'SV2',       name: 'Paldea Evolved' },
  { code: 'SV3',       name: 'Obsidian Flames' },
  { code: 'SV4',       name: 'Paradox Rift' },
  { code: 'SV5',       name: 'Temporal Forces' },
  { code: 'SV6',       name: 'Twilight Masquerade' },
  { code: 'SV7',       name: 'Stellar Crown' },
  { code: 'SV8',       name: 'Surging Sparks' },
  { code: 'SPEC-SL',   name: 'Shining Legends' },
  { code: 'SPEC-HF',   name: 'Hidden Fates' },
  { code: 'SPEC-CP',   name: "Champion's Path" },
  { code: 'SPEC-SF',   name: 'Shining Fates' },
  { code: 'SPEC-CZ',   name: 'Crown Zenith' },
  { code: 'SPEC-DET',  name: 'Detective Pikachu' },
  { code: 'SPEC-GEN',  name: 'Generations' },
  { code: 'SPEC-DRM',  name: 'Dragon Majesty' },
  { code: 'SPEC-GO',   name: 'Pokémon GO' },
  { code: 'SPEC-151',  name: 'Pokémon 151' },
  { code: 'SPEC-PRC',  name: 'Prismatic Evolutions' },
  { code: 'SPEC-CEL',  name: 'Celebrations' },
  { code: 'PROMO-WOTC', name: 'WOTC Black Star Promo' },
  { code: 'PROMO-NP',   name: 'Nintendo Promo' },
  { code: 'PROMO-DPP',  name: 'DP Black Star Promo' },
  { code: 'PROMO-HGSS', name: 'HGSS Promo' },
  { code: 'PROMO-BW',   name: 'BW Promo' },
  { code: 'PROMO-XY',   name: 'XY Promo' },
  { code: 'PROMO-SM',   name: 'SM Promo' },
  { code: 'PROMO-SWSH', name: 'SWSH Promo' },
  { code: 'PROMO-SV',   name: 'SV Promo' },
];

export const JP_SETS: SetEntry[] = [
  { code: 'BS1',       name: 'Expansion Pack (Basic)' },
  { code: 'JG',        name: 'Jungle' },
  { code: 'FO',        name: 'Fossil' },
  { code: 'TR',        name: 'Rocket Gang' },
  { code: 'GY1',       name: 'Gym Heroes' },
  { code: 'GY2',       name: 'Gym Challenge' },
  { code: 'NEO1',      name: 'Neo Genesis' },
  { code: 'NEO2',      name: 'Neo Discovery' },
  { code: 'NEO3',      name: 'Neo Revelation' },
  { code: 'NEO4',      name: 'Neo Destiny' },
  { code: 'E1',        name: 'Expedition' },
  { code: 'E2',        name: 'Aquapolis' },
  { code: 'E3',        name: 'Skyridge' },
  { code: 'VS',        name: 'VS Series' },
  { code: 'WEB',       name: 'Web Series' },
  { code: 'CD96',      name: 'Bandai Carddass Vending' },
  { code: 'CD97',      name: 'Pocket Monsters Carddass' },
  { code: 'VEND',      name: 'Vending Series' },
  { code: 'ADV1',      name: 'ADV Expansion Pack' },
  { code: 'ADV2',      name: 'Miracle of the Desert' },
  { code: 'ADV3',      name: 'Rulers of the Heavens' },
  { code: 'ADV4',      name: 'Team Magma vs Aqua' },
  { code: 'ADV5',      name: 'Hidden Legends' },
  { code: 'ADV6',      name: 'FireRed & LeafGreen' },
  { code: 'ADV7',      name: 'Rocket Returns' },
  { code: 'ADV8',      name: 'Deoxys' },
  { code: 'ADV9',      name: 'Emerald' },
  { code: 'ADV10',     name: 'Unseen Forces' },
  { code: 'ADV11',     name: 'Delta Species' },
  { code: 'ADV12',     name: 'Legend Maker' },
  { code: 'ADV13',     name: 'Holon Phantoms' },
  { code: 'ADV14',     name: 'Crystal Guardians' },
  { code: 'ADV15',     name: 'Dragon Frontiers' },
  { code: 'ADV16',     name: 'Power Keepers' },
  { code: 'DP1',       name: 'Diamond & Pearl' },
  { code: 'DP2',       name: 'Mysterious Treasures' },
  { code: 'DP3',       name: 'Secret Wonders' },
  { code: 'DP4',       name: 'Great Encounters' },
  { code: 'DP5',       name: 'Majestic Dawn' },
  { code: 'DP6',       name: 'Legends Awakened' },
  { code: 'DP7',       name: 'Stormfront' },
  { code: 'PL1',       name: 'Platinum' },
  { code: 'PL2',       name: 'Rising Rivals' },
  { code: 'PL3',       name: 'Supreme Victors' },
  { code: 'PL4',       name: 'Arceus' },
  { code: 'HGSS1',     name: 'HeartGold' },
  { code: 'HGSS2',     name: 'SoulSilver' },
  { code: 'HGSS3',     name: 'Lost Link' },
  { code: 'HGSS4',     name: 'Triumphant' },
  { code: 'HGSS-REV',  name: 'Reviving Legends' },
  { code: 'HGSS-GOL',  name: 'Golden Sky, Silvery Ocean' },
  { code: 'HGSS-TCG',  name: 'Clash at the Summit' },
  { code: 'BW1',       name: 'Black Collection' },
  { code: 'BW2',       name: 'White Collection' },
  { code: 'BW3',       name: 'Emerging Powers' },
  { code: 'BW4',       name: 'Dark Rush' },
  { code: 'BW5',       name: 'Dragons Exalted' },
  { code: 'BW6',       name: 'Cold Flare' },
  { code: 'BW7',       name: 'Plasma Gale' },
  { code: 'BW8',       name: 'Plasma Freeze' },
  { code: 'BW9',       name: 'Megalo Cannon' },
  { code: 'BW-EX',     name: 'EX Battle Boost' },
  { code: 'BW-WB',     name: 'Wild Blaze' },
  { code: 'BW-SD',     name: 'Shining Darkness' },
  { code: 'BW-BF',     name: 'Beat of the Frontier' },
  { code: 'BW-GC',     name: "Galactic's Conquest" },
  { code: 'XY1',       name: 'Collection X' },
  { code: 'XY2',       name: 'Collection Y' },
  { code: 'XY3',       name: 'Rising Fist' },
  { code: 'XY4',       name: 'Phantom Gate' },
  { code: 'XY5',       name: 'Gaia Volcano' },
  { code: 'XY6',       name: 'Tidal Storm' },
  { code: 'XY7',       name: 'Bandit Ring' },
  { code: 'XY8',       name: 'Blue Shock' },
  { code: 'XY9',       name: 'Red Flash' },
  { code: 'XY10',      name: 'Rage of Broken Heavens' },
  { code: 'XY11',      name: 'Explosive Fighter' },
  { code: 'XY12',      name: 'Cruel Traitor' },
  { code: 'XY-LSC',    name: 'Legendary Shine Collection' },
  { code: 'XY-POK',    name: 'Pokekyun Collection' },
  { code: 'XY-HMC',    name: 'Hyper Metal Chain Deck' },
  { code: 'XY-20TH',   name: '20th Anniversary Expansion' },
  { code: 'SM1',       name: 'Collection Sun' },
  { code: 'SM2',       name: 'Collection Moon' },
  { code: 'SM3',       name: 'Islands Awaiting You' },
  { code: 'SM4',       name: 'Awakening Psychic King' },
  { code: 'SM5',       name: 'Ultra Sun' },
  { code: 'SM6',       name: 'Ultra Moon' },
  { code: 'SM7',       name: 'Dragon Storm' },
  { code: 'SM8',       name: 'Super Burst Impact' },
  { code: 'SM9',       name: 'Tag Bolt' },
  { code: 'SM10',      name: 'Double Blaze' },
  { code: 'SM11',      name: 'Miracle Twin' },
  { code: 'SM12',      name: 'Alter Genesis' },
  { code: 'SM-MC',     name: 'Miracle Crystal' },
  { code: 'SM-NUN',    name: 'Night Unison' },
  { code: 'SM-FMW',    name: 'Full Metal Wall' },
  { code: 'SM-RMX',    name: 'Remix Bout' },
  { code: 'SM-USG',    name: 'Ultra Shiny GX' },
  { code: 'SM-DRL',    name: 'Dream League' },
  { code: 'SM-SKY',    name: 'Sky Legend' },
  { code: 'SM-GO',     name: 'Pokémon GO (JP)' },
  { code: 'SPEC-SM12a', name: 'Tag All Stars' },
  { code: 'SWSH1',     name: 'Sword' },
  { code: 'SWSH2',     name: 'Shield' },
  { code: 'SWSH3',     name: 'VMAX Rising' },
  { code: 'SWSH4',     name: 'Rebellion Crash' },
  { code: 'SWSH5',     name: 'Infinity Zone' },
  { code: 'SWSH6',     name: 'Amazing Volt Tackle' },
  { code: 'SWSH7',     name: 'Single Strike Master' },
  { code: 'SWSH8',     name: 'Rapid Strike Master' },
  { code: 'SWSH9',     name: 'Jet-Black Spirit' },
  { code: 'SWSH10',    name: 'Silver Lance' },
  { code: 'SWSH11',    name: 'Blue Sky Stream' },
  { code: 'SWSH12',    name: 'Eevee Heroes' },
  { code: 'SWSH13',    name: 'Fusion Arts' },
  { code: 'SWSH-SB',   name: 'Star Birth' },
  { code: 'SWSH-TG',   name: 'Time Gazer' },
  { code: 'SWSH-SJ',   name: 'Space Juggler' },
  { code: 'SWSH-DP',   name: 'Dark Phantasma' },
  { code: 'SWSH-IA',   name: 'Incandescent Arcana' },
  { code: 'SWSH-PT',   name: 'Paradigm Trigger' },
  { code: 'SWSH-BR',   name: 'Battle Region' },
  { code: 'SWSH-LA',   name: 'Lost Abyss' },
  { code: 'CLF',       name: 'TCG Classic (Venusaur/Lugia)' },
  { code: 'CLL',       name: 'TCG Classic (Charizard/Ho-Oh)' },
  { code: 'CLK',       name: 'TCG Classic (Blastoise/Suicune)' },
  { code: 'SV1',       name: 'Scarlet ex' },
  { code: 'SV1V',      name: 'Violet ex' },
  { code: 'SV1a',      name: 'Triplet Beat' },
  { code: 'SV2',       name: 'Snow Hazard' },
  { code: 'SV2a',      name: 'Pokémon Card 151' },
  { code: 'SV3',       name: 'Ruler of the Black Flame' },
  { code: 'SV3a',      name: 'Raging Surf' },
  { code: 'SV4',       name: 'Ancient Roar' },
  { code: 'SV4a',      name: 'Shiny Treasure ex' },
  { code: 'SV5',       name: 'Cyber Judge / Clay Burst' },
  { code: 'SV5a',      name: 'Wild Force' },
  { code: 'SV6',       name: 'Mask of Change' },
  { code: 'SV6a',      name: 'Night Wanderer' },
  { code: 'SV7',       name: 'Stellar Miracle' },
  { code: 'SV7a',      name: 'Paradise Dragona' },
  { code: 'SV8',       name: 'Super Electric Breaker' },
  { code: 'SV8a',      name: 'Terastal Fest ex' },
  { code: 'SV9',       name: 'Battle Partners' },
  { code: 'SV9a',      name: 'Heat Wave Arena' },
  { code: 'SV11W',     name: 'White Flare' },
  { code: 'SV11B',     name: 'Black Bolt' },
  { code: 'M1L',       name: 'Mega Brave' },
  { code: 'M1S',       name: 'Mega Symphonia' },
  { code: 'SV-CH',     name: 'Crimson Haze' },
  { code: 'SV-FF',     name: 'Future Flash' },
  { code: 'SV-TM',     name: 'Transformation Mask' },
  { code: 'SV-US',     name: 'Undone Seal' },
  { code: 'SV-DD',     name: 'Dawn Dash' },
  { code: 'SV-WCP',    name: 'World Champions Pack' },
  { code: 'SPEC-CP6',  name: '20th Anniversary (CP6)' },
  { code: 'SPEC-S4a',  name: 'Shiny Star V' },
  { code: 'SPEC-S8a',  name: 'VMAX Climax' },
  { code: 'SPEC-S12a', name: 'VSTAR Universe' },
  { code: 'SPEC-SV4a', name: 'Shiny Treasure ex' },
  { code: 'PROMO-P',    name: 'Classic / Corocoro Promo' },
  { code: 'PROMO-DP',   name: 'DP-P Promo' },
  { code: 'PROMO-PCG',  name: 'PCG Promo' },
  { code: 'PROMO-HGSS', name: 'HGSS Promo' },
  { code: 'PROMO-BW',   name: 'BW-P Promo' },
  { code: 'PROMO-XY',   name: 'XY-P Promo' },
  { code: 'PROMO-SM',   name: 'SM-P Promo' },
  { code: 'PROMO-SWSH', name: 'S-P Promo' },
  { code: 'PROMO-SV',   name: 'SV-P / M-P Promo' },
];

export function filterSets(lang: 'JP' | 'EN', query: string): SetEntry[] {
  const sets = lang === 'JP' ? JP_SETS : EN_SETS;
  if (!query) return sets;
  const q = query.toLowerCase();
  return sets.filter(
    (s) => s.code.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)
  );
}
